### ISSUE TITLE
Crash when App launch

### ISSUE THREAD

**Issue by trihung93** [Swati4star/Travel-Mate#11]
I got an error like this for the first time app launch
I use Genymotion Samsung s6 6.0.0

02-08 10:26:51.153 3579-3594/tie.hackathon.travelguide E/AndroidRuntime: FATAL EXCEPTION: BeaconServiceThread
                                                                         Process: tie.hackathon.travelguide, PID: 3579
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.isEnabled()' on a null object reference
                                                                             at com.estimote.sdk.service.internal.JellyBeanBluetoothAdapter.start(JellyBeanBluetoothAdapter.java:43)
                                                                             at com.estimote.sdk.service.internal.CycleBluetoothScanner.start(CycleBluetoothScanner.java:64)
                                                                             at com.estimote.sdk.service.BeaconService.startScanning(BeaconService.java:336)
                                                                             at com.estimote.sdk.service.BeaconService.startMonitoring(BeaconService.java:286)
                                                                             at com.estimote.sdk.service.BeaconService.access$300(BeaconService.java:69)
                                                                             at com.estimote.sdk.service.BeaconService$IncomingHandler$1.run(BeaconService.java:440)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
02-08 10:26:51.670 3579-3592/tie.hackathon.travelguide E/Surface: getSlotFromBufferLocked: unknown buffer: 0xdf0e9a60

**Comment by Swati4star** [comment]
Thank you.

Fixed by 1ac3c5fb60aa110115275537b38c041a5c00a69f
