### ISSUE TITLE
Crash at app launch

### ISSUE THREAD

**Issue by oofoamalu** [Swati4star/Travel-Mate#15]
Find stacktrace below:

05-12 13:23:39.579 21992-21992/tie.hackathon.travelguide E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: tie.hackathon.travelguide, PID: 21992
                                                                           java.lang.NoSuchMethodError: No static method setOnApplyWindowInsetsListener(Landroid/view/View;Landroid/support/v4/view/OnApplyWindowInsetsListener;)V in class Landroid/support/v4/view/ViewCompatLollipop; or its super classes (declaration of 'android.support.v4.view.ViewCompatLollipop' appears in /data/app/tie.hackathon.travelguide-1/base.apk)
                                                                               at android.support.v4.view.ViewCompat$LollipopViewCompatImpl.setOnApplyWindowInsetsListener(ViewCompat.java:1558)
                                                                               at android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(ViewCompat.java:2819)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:410)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:300)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:264)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                                               at tie.hackathon.travelguide.Splash.onCreate(Splash.java:17)
                                                                               at android.app.Activity.performCreate(Activity.java:6237)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)[](url)

**Comment by hanmeimei888** [comment]
compile('com.jakewharton:butterknife:8.5.1') {
    exclude module: 'appcompat-v7'
    exclude group: 'com.android.support'
}

**Comment by hanmeimei888** [comment]
and don‘t forget 'annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'

**Comment by hanmeimei888** [comment]
you may meet the questions like ‘No such file’ ....just trust me and clean project

**Comment by hanmeimei888** [comment]
(your head is so beautiful

**Comment by oofoamalu** [comment]
Thanks!

I added the following:

```
compile ('com.jakewharton:butterknife:8.5.1')  {
    exclude module:'appcompat-v7', group:'com.android.support'
}
```
That solved the crash.

Also on the side, I used the latest appcompat-v7 versions

Is there a need to submit a PR for this? I'm not certain if anyone has experienced this crash before.

**Comment by hanmeimei888** [comment]
yeah , i think we should do this.
someone i have know is suffering with this issue too,
in fact i have met this crash before by 'fresco'..etc..，in this project i think it's caused by
'com.jakewharton:butterknife:8.5.1'.
can you do this? I'm new guy for github,not familiar with operation

ps: i have 0 followers now ,could you click following for me ? It's just a cutie's hope...

**Comment by prabhakar267** [comment]
@Swati4star please check if there is a need to add this to the code or not
mention : @oofoamalu
