### ISSUE TITLE
App crashes on registration/login

### ISSUE THREAD

**Issue by zeshan-rana7** [Swati4star/Travel-Mate#55]
As soon as I press login or register button, app crashes.

Here are stack traces:
FATAL EXCEPTION: OkHttp Dispatcher
                                                                         Process: tie.hackathon.travelguide, PID: 2617
                                                                         java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
                                                                             at android.widget.Toast$TN.<init>(Toast.java:390)
                                                                             at android.widget.Toast.<init>(Toast.java:114)
                                                                             at android.widget.Toast.makeText(Toast.java:277)
                                                                             at android.widget.Toast.makeText(Toast.java:267)
                                                                             at tie.hackathon.travelguide.login.LoginActivity.showError(LoginActivity.java:135)
                                                                             at tie.hackathon.travelguide.login.LoginPresenter$1.onFailure(LoginPresenter.java:61)
                                                                             at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                             at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                             at java.lang.Thread.run(Thread.java:764)
05-16 19:21:05.693 2617-2636/tie.hackathon.travelguide D/EGL_emulation: eglMakeCurrent: 0xa855eb40: ver 3 0 (tinfo 0xa8561820)
05-16 19:21:06.517 2617-2617/tie.hackathon.travelguide E/WindowManager: android.view.WindowLeaked: Activity tie.hackathon.travelguide.login.LoginActivity has leaked window DecorView@11fdb43[] that was originally added here
                                                                            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
                                                                            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
                                                                            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                            at android.app.Dialog.show(Dialog.java:330)
                                                                            at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1350)
                                                                            at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1341)
                                                                            at tie.hackathon.travelguide.login.LoginActivity.showLoadingDialog(LoginActivity.java:145)
                                                                            at tie.hackathon.travelguide.login.LoginPresenter.ok_signUp(LoginPresenter.java:47)
                                                                            at tie.hackathon.travelguide.login.LoginActivity.onClick(LoginActivity.java:112)
                                                                            at android.view.View.performClick(View.java:6294)
                                                                            at android.view.View$PerformClick.run(View.java:24770)
                                                                            at android.os.Handler.handleCallback(Handler.java:790)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Swati4star** [comment]
I have added a fix for this issue. We were getting error in the response : "Expected ':status' header not present". Updating okhttp to the latest version fixed this issue.
Closing it for now. If you face any problem, feel free to reopen the issue.
